// Helper de preposição correta por localidade (PT-BR).
// "no Tatuapé", "na Mooca", "em Alphaville", etc.

export type Preposition = "em" | "no" | "na" | "nos" | "nas";

// Overrides explícitos por nome exato — sempre prevalecem sobre heurísticas.
const OVERRIDES: Record<string, Preposition> = {
  // Zona Leste
  "Tatuapé": "no",
  "Mooca": "na",
  "Belém": "no",
  "Brás": "no",
  "Carrão": "no",
  "Vila Carrão": "na",
  "Penha": "na",
  "Vila Formosa": "na",
  "Arthur Alvim": "no",
  "Ermelino Matarazzo": "em",
  "Iguatemi": "no",
  "Tatuapé ": "no",
  "Anália Franco": "na",
  "Jardim Anália Franco": "no",
  "Itaquera": "em",
  "Sapopemba": "em",
  "São Mateus": "em",
  "São Miguel Paulista": "em",
  "São Lucas": "em",
  "Cidade Tiradentes": "na",
  "Cidade Líder": "na",
  "Cidade Patriarca": "na",
  "Vila Prudente": "na",
  "Vila Matilde": "na",
  "Vila Jacuí": "na",
  "Vila Curuçá": "na",
  "Vila Zelina": "na",
  "Parque do Carmo": "no",
  "Ponte Rasa": "na",
  "Cangaíba": "em",
  "Lajeado": "no",
  "Guaianases": "em",
  "Itaim Paulista": "no",
  "Jardim Helena": "no",
  "Jardim Aricanduva": "no",
  "Americanópolis": "em",

  // Centro
  "Aclimação": "na",
  "Anhanguera": "em", // nome ambíguo (rodovia/faculdade) — locativa segura
  "Bela Vista": "na",
  "Bom Retiro": "no",
  "Cambuci": "no",
  "Campos Elíseos": "nos",
  "Consolação": "na",
  "Higienópolis": "em",
  "Jardins": "nos",
  "Liberdade": "na",
  "Pacaembu": "no",
  "Pari": "no",
  "República": "na",
  "Santa Cecília": "em",
  "Santa Efigênia": "em",
  "Sé": "na",
  "Vila Buarque": "na",
  "Avenida Paulista": "na",

  // Zona Norte
  "Perus": "em",
  "Freguesia do Ó": "na",
  "Casa Verde": "na",
  "Bairro do Limão": "no",
  "Vila Maria": "na",
  "Vila Nova Cachoeirinha": "na",
  "Vila Guilherme": "na",
  "Santana": "em",
  "Parada Inglesa": "na",
  "Brasilândia": "na",
  "Água Fria": "na",
  "Lauzane Paulista": "em",
  "Mandaqui": "no",
  "Jardim Peri Peri": "no",
  "Imirim": "no",
  "Jaçanã": "no",
  "Tremembé": "no",
  "Tucuruvi": "no",
  "Vila Medeiros": "na",
  "José Bonifácio": "em",
  "Horto Florestal": "no",
  "Santa Terezinha": "em",

  // Zona Oeste
  "Água Branca": "na",
  "Alphaville": "em",
  "Alto da Lapa": "no",
  "Alto de Pinheiros": "no",
  "Amador Bueno": "em",
  "Barra Funda": "na",
  "Barueri": "em",
  "Butantã": "no",
  "Carapicuíba": "em",
  "Caxingui": "no",
  "Cotia": "em",
  "Embu das Artes": "em",
  "Granja Viana": "na",
  "Itapevi": "em",
  "Jaguaré": "no",
  "Jandira": "em",
  "Jaraguá": "no",
  "Lapa": "na",
  "Osasco": "em",
  "Parque dos Príncipes": "no",
  "Parque São Domingos": "no",
  "Perdizes": "em",
  "Pinheiros": "em",
  "Pirituba": "em",
  "Pompéia": "na",
  "Presidente Altino": "em",
  "Quitaúna": "em",
  "Raposo Tavares": "no",
  "Rio Pequeno": "no",
  "Santana de Parnaíba": "em",
  "Sumaré": "no",
  "Taboão da Serra": "em",
  "Vila dos Remédios": "na",
  "Vila Jaguara": "na",
  "Vila Leopoldina": "na",
  "Vila Madalena": "na",
  "Vila Romana": "na",
  "Vila São Francisco": "na",

  // Zona Sul
  "Jardim América": "no",
  "Jardim Europa": "no",
  "Cidade Jardim": "na",
  "Brooklin": "no",
  "Ibirapuera": "no",
  "Ipiranga": "no",
  "Morumbi": "no",
  "Panamby": "no",
  "Paraíso": "no",
  "Paraisópolis": "em",
  "Parelheiros": "em",
  "Sacomã": "no",
  "Santo Amaro": "em",
  "Vila Olímpia": "na",
  "Vila Sônia": "na",
  "Vila Mariana": "na",
  "Vila Gumercindo": "na",
  "Saúde": "na",
  "Interlagos": "em",
  "Água Funda": "na",
  "Alto da Boa Vista": "no",
  "Bosque da Saúde": "no",
  "Campo Belo": "no",
  "Campo Grande": "no",
  "Campo Limpo": "no",
  "Capela do Socorro": "na",
  "Capão Redondo": "no",
  "Chácara Flora": "na",
  "Chácara Santo Antônio": "na",
  "Chácara Klabin": "na",
  "Cidade Ademar": "na",
  "Cidade Avelino": "na",
  "Cidade Dutra": "na",
  "Cursino": "no",
  "Grajaú": "no",
  "Granja Julieta": "na",
  "Heliópolis": "em",
  "Horto do Ipê": "no",
  "Itaim Bibi": "no",
  "Itapecerica da Serra": "em",
  "Jabaquara": "no",
  "Jardim Ângela": "no",
  "Jardim Ipanema": "no",
  "Jardim Marajoara": "no",
  "Jardim Paulista": "no",
  "Jardim São Luís": "no",
  "Jardim Sul": "no",
  "Jurubatuba": "em",
  "Marsilac": "em",
  "M'Boi Mirim": "no",
  "Mirandópolis": "em",
  "Moema": "em",
  "Pedreira": "na",
  "Real Parque": "no",
  "São Judas": "no",
  "São Rafael": "no",
  "Vila Andrade": "na",
  "Vila Clementino": "na",
  "Vila das Mêrces": "nas",
  "Vila Mascote": "na",
  "Vila Nova Conceição": "na",
  "Vila Santa Catarina": "na",

  // Outras (cidades) — geralmente "em"
  "Cajamar": "em",
  "Campinas": "em",
  "Aeroporto": "no",
  "Cumbica": "em",
  "Guarulhos": "em",
  "Jundiaí": "em",
  "Abc Paulista": "no",
  "Americana": "em",
  "Araçariguama": "em",
  "Araraquara": "em",
  "Bauru": "em",
  "Bragança Paulista": "em",
  "Diadema": "em",
  "Embu Guaçu": "em",
  "Ferraz de Vasconcelos": "em",
  "Franca": "em",
  "Franco da Rocha": "em",
  "Guarujá": "no",
  "Hortolândia": "em",
  "Indaiatuba": "em",
  "Itanhaém": "em",
  "Itaquaquecetuba": "em",
  "Itu": "em",
  "Jacareí": "em",
  "Limeira": "em",
  "Marília": "em",
  "Mauá": "em",
  "Mogi das Cruzes": "em",
  "Mongaguá": "em",
  "Monte Mor": "em",
  "Peruíbe": "em",
  "Piracicaba": "em",
  "Poá": "em",
  "Praia Grande": "na",
  "Presidente Prudente": "em",
  "Ribeirão Pires": "em",
  "Santo André": "em",
  "Santos": "em",
  "São Bernardo do Campo": "em",
  "São Caetano do Sul": "em",
  "São Carlos": "em",
  "São José do Rio Preto": "em",
  "São José dos Campos": "em",
  "São Vicente": "em",
  "Serra da Cantareira": "na",
  "Sorocaba": "em",
  "Suzano": "em",
  "Taubaté": "em",
  "Vargem Grande Paulista": "em",
  "Vila Caiçara": "na",
  "Vinhedo": "em",
};

export function getPreposition(name: string): Preposition {
  if (OVERRIDES[name]) return OVERRIDES[name];
  // Heurística por prefixo
  const lower = name.toLowerCase();
  if (lower.startsWith("vila ") || lower.startsWith("avenida ") || lower.startsWith("praia ") ||
      lower.startsWith("chácara ") || lower.startsWith("cidade ") || lower.startsWith("granja ") ||
      lower.startsWith("serra ") || lower.startsWith("freguesia ") || lower.startsWith("casa "))
    return "na";
  if (lower.startsWith("jardim ") || lower.startsWith("parque ") || lower.startsWith("alto ") ||
      lower.startsWith("bosque ") || lower.startsWith("campo ") || lower.startsWith("bairro ") ||
      lower.startsWith("horto "))
    return "no";
  if (lower.startsWith("jardins") || lower.startsWith("campos "))
    return "nos";
  return "em";
}

// "Terraplanagem no Tatuapé", "Terraplanagem em Alphaville", etc.
export function getLocationPhrase(name: string): string {
  return `${getPreposition(name)} ${name}`;
}

export function getKeywordWithLocation(service: string, name: string): string {
  return `${service} ${getLocationPhrase(name)}`;
}
